### ISSUE TITLE
Bypass anti-scraping 

### ISSUE THREAD

**Issue by ryanxjhan** [zackthoutt/wine-deep-learning#1]
It looks like that the site has implemented some kind of anti-scraping mechanism. The site will ban me from accessing it for about 100 reviews scraped. Is there a solution to this?

**Comment by manycoding** [comment]
You could limit the number of concurrent requests, default it's 10.
10 works for me without any ban.

**Comment by zackthoutt** [comment]
You can also try scraping from a different IP. They (understandably) may have more sophisticated anti-scraping software now that black lists IP addresses if you hammer the site too hard.
